from typing import Optional
from utils import generate_unique_id
from common_constants.support import ID_PATTERN
from pydantic import BaseModel, Field, computed_field

from enum import IntEnum

class RequestStatus(IntEnum):
    QUEUED = 1
    RETRIEVING_POSTS = 2
    QUEUED_PROMPT = 3
    GENERATING_WELCOME_MESSAGE = 4
    COMPLETED = 5
    FAILED = 6

class Post(BaseModel):
    post_content: str = Field(...)
    time_ago: Optional[str] = Field(None)

class BaseLnkdRequestModel(BaseModel):
    lnkd_request_id: str = Field(default_factory=generate_unique_id, description="The unique linkedin scraping and message requestid")
    tagret_profile: str = Field(...)

    # Target meta
    target_headline: Optional[str] = Field(None)
    target_name: Optional[str] = Field(None)
    target_about: Optional[str] = Field(None)

    posts: Optional[list[Post]] = Field(None, description="Scraped Posts")
    message: Optional[str] = Field(None, description="Greeting Message generated by the LLM")
    
    status_message: str = Field(...)
    status: RequestStatus = Field(RequestStatus.QUEUED)

class LnkdRequestDao(BaseLnkdRequestModel):

    request_id: str = Field(..., pattern=ID_PATTERN, description="The api call this request is associated to. In future one api request id might be associated to multiple lnkd_request_id 's")
    user_id: str = Field(..., pattern=ID_PATTERN)
    
    # All of these fields should have some constraints on length idealy but i don't have enough time as of now to research all of these constraints
    lnkd_username: str = Field(...) # should be encrypted ideally, not doing it here, considering it out of scope for the assignment
    lnkd_password: str = Field(...) # should be encrypted ideally, not doing it here, considering it out of scope for the assignment

    @computed_field
    @property
    def linkedin_url(self) -> str:
        """
        - This will not work for cases where the user has not yet configured a custom profile url
        But I'm going to ignore those cases now. Will need more time to think about how to safely include those accounts as well
        
        - Even this implementation leaves possible vulnerabilities wherein someone can add a query or some additional flags to the linkedin profile url
        Not very safe but i don't have time to think of it as of now. Possibly a simple regex in target_profile validation should help this.
        """
        return f"https://www.linkedin.com/in/{self.tagret_profile}"